skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release

skip_commits:
  message: /\[WIP\]/

install:
  - cinst gitversion.portable
  - nuget restore
  - ps: gitversion /l console /output buildserver
  - ps: $env:preview = $APPVEYOR_REPO_BRANCH -match "release/.*"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(GitVersion_FullSemVer)
  package_version: $(GitVersion_FullSemVer)
  assembly_version: $(GitVersion_AssemblySemVer)
  file_version: $(GitVersion_AssemblySemVer)
  informational_version: $(GitVersion_FullSemVer)


on_failure:
  - ps: 7z a "WorkingTree.zip"
  - ps: Push-AppveyorArtifact WorkingTree.zip

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  verbosity: minimal



deploy:
- provider: GitHub
  auth_token:
    secure: BZITyDe4tvA5gKlOwmULjb2Q+D5LZK1eJeKdSkqXtlDEYU1AA6+UMYQ9J   c/3CXwQ
  on:
    branch: master
- provider: GitHub
  prerelease: true
  auth_token:
    secure: BZITyDe4tvA5gKlOwmULjb2Q+D5LZK1eJeKdSkqXtlDEYU1AA6+UMYQ9Jc/3CXwQ
  on:
    preview: true
- provider: NuGet
  api_key:
    secure: DMMq9J7b9JR07KcGPL8CjIGzX7ABeneI3RLcvd5dMz0r1k9pOcpSNmcwEd/KTgog
  on:
    branch: master